[build]
  command = "npm run check && npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
